name: Fetch contributors list of openebs and write into json

on:

  schedule:
    - cron: '*/10 * * * *' #job schedule on midnight everyday
  push:
    branches: [ main ]
    paths: ['./website/src/resources/contributors.json']
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  resources:
    name: Update resource
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: install dep
        run: npm install request
      - name: Run a one-line script
        working-directory: ./website
        run: npm run getContributors
      - name: git operations
        run: |
         git status
         git config user.name rakesh
         git config user.email rakesh.pr@mayadata.io
         git add .
         git commit -m "updating contributor"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.TOKEN }}
         force: true
