# This is a basic workflow to help you get started with Actions

name: CI

on:

  schedule:
    #- cron: '*/10 * * * *'
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  resources:
    name: Update resources
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: install dep
        run: npm install request
      - name: Get contributors
        working-directory: ./website
        run: npm run getContributors
      - name: check for changes
        run: |
         git status
         git config user.name rakesh
         git config user.email rakesh.pr@mayadata.io
         git add .
         git commit -m "Update contributor list"
         git push
      #- name: Push changes
       # uses: ad-m/github-push-action@master
        #with:
         #github_token: ${{ secrets.TOKEN }}
         #force: true
