# This is a basic workflow to help you get started with Actions

name: CI



# Controls when the workflow will run
on:

  schedule:
    - cron: '*/10 * * * *'
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  resources:
    name: Update resources
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: install dep
        run: npm install request
      - name: Run a one-line script
        working-directory: ./website
        run: npm run getContributors
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.TOKEN }}
      - name: check for changes
        run: |
         git status
         git config user.name github-actions
         git config user.email github-actions@github.com
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating TODO.txt"
      - name: fetch from master
        run: git fetch origin main
      - name: push code to main
        run: git push origin HEAD:main
      #- name: Update resources
       # uses: test-room-7/action-update-file@v1
        #with:
         #file-path: ./website/src/resources/contributors.json
         #commit-msg: Update resources
         #github-token: ${{ secrets.TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    ##steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
       # working-directory: ./website
       # run: npm run getContributors
