name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/611d588b20b42600bffd7e3c
